### ISSUE TITLE
Builds are empty

### ISSUE THREAD

**Issue by mcmillion** [game-ci/steam-deploy#12]
Here's my current config:

```yaml
name: Build and Release
on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Build for Standalone Windows
        id: build_windows
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: StandaloneWindows
          buildName: Game

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Generate Steam MFA
        id: generate_steam_mfa
        uses: CyberAndrii/steam-totp@v1
        with:
          shared_secret: ${{ secrets.STEAM_SHARED_SECRET }}

      - name: Deploy to Steam
        uses: webbertakken/steam-deploy@v0.1
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          mfaCode:  ${{ steps.generate_steam_mfa.outputs.code }}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: ${{ steps.build_windows.outputs.buildVersion }}
          rootPath: build
          depot1Path: StandaloneWindows
          releaseBranch: default
```

Everything seems to work up until it uploads, then I get the following error:

```
uilding file mapping...
Scanning content
Uploading content
[2021-06-16 06:23:16]: ERROR! Failed to commit build for AppID *** : Failure

#################################
#        Current status         #
#################################

Show the current state of the app on this client.
/entrypoint.sh: 24: /steps/5_execute_steamcmd.sh: /home/steam/steamcmd/steamcmd.sh +app_status ***: not found

Show the current Steamworks configuration for this game (depots, launch options, etc.). ***
/entrypoint.sh: 28: /steps/5_execute_steamcmd.sh: /home/steam/steamcmd/steamcmd.sh +app_info_print manifest.vdf: not found

Show the current user configuration for this game (current language, install directory, etc.)
/entrypoint.sh: 32: /steps/5_execute_steamcmd.sh: /home/steam/steamcmd/steamcmd.sh +app_config_print ***: not found

#################################
#             Errors            #
#################################

Listing current folder and rootpath

total 84K
drwxr-xr-x 15 1001  121 4.0K Jun 16 06:22 .
drwxr-xr-x  6 root root 4.0K Jun 16 06:22 ..
drwxr-xr-x  9 1001  121 4.0K Jun 16 06:17 .git
-rw-r--r--  1 1001  121 2.1K Jun 16 06:17 .gitattributes
drwxr-xr-x  3 1001  121 4.0K Jun 16 06:17 .github
-rw-r--r--  1 1001  121 1.9K Jun 16 06:17 .gitignore
drwxr-xr-x  2 1001  121 4.0K Jun 16 06:17 .vscode
drwxr-xr-x 11 1001  121 4.0K Jun 16 06:21 Assets
drwxr-xr-x  2 root root 4.0K Jun 16 06:22 BuildOutput
drwxr-xr-x 13 1001  121 4.0K Jun 16 06:21 Library
drwxr-xr-x  2 root root 4.0K Jun 16 06:21 Logs
drwxr-xr-x  2 1001  121 4.0K Jun 16 06:17 Originals
drwxr-xr-x  2 1001  121 4.0K Jun 16 06:17 Packages
drwxr-xr-x  3 1001  121 4.0K Jun 16 06:21 ProjectSettings
drwxr-xr-x  2 root root 4.0K Jun 16 06:21 UserSettings
drwxr-xr-x  3 root root 4.0K Jun 16 06:21 build
-rw-r--r--  1 root root  213 Jun 16 06:22 depot1666371.vdf
-rw-r--r--  1 root root  222 Jun 16 06:22 manifest.vdf
-rw-r--r--  1 1001  121  889 Jun 16 06:17 omnisharp.json
-rw-r--r--  1 1001  121    7 Jun 16 06:17 steam_appid.txt
drwxr-xr-x  3 1001  121 4.0K Jun 16 06:22 steamcmd

total 12K
drwxr-xr-x  3 root root 4.0K Jun 16 06:21 .
drwxr-xr-x 15 1001  121 4.0K Jun 16 06:22 ..
drwxr-xr-x  4 root root 4.0K Jun 16 06:21 StandaloneWindows
```

So a couple of things to note:
- The build artifact is there. I can download it and it has the files, and it runs
- It seems to be finding the root folder and it matches the build
- Builds are showing up in my Steam dashboard, but their sizes are 0.0B

Any idea what may be going wrong?
