### ISSUE TITLE
Deployment fails during upload - libcurl.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by toriath** [game-ci/steam-deploy#33]
**Bug description**

Steam deployment fails during build upload.
Setup steam account and deployment pipe as per documentation and double-checked the github secrets. 

```yml
  deployToSteam:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download StandaloneWindows64 Artifact
        uses: actions/download-artifact@v2
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64
      - name: Get Version
        id: versioning
        uses: paulhatch/semantic-version@v4.0.2
        with:
          format: "${major}.${minor}.${patch}"
      - uses: game-ci/steam-deploy@v1
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
          ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: v${{ steps.versioning.outputs.version }}
          rootPath: build
          depot1Path: StandaloneWindows64
          #depot2Path: StandaloneLinux64
          releaseBranch: experimental

```

```
Displaying error log

CAppInfoCacheReadFromDiskThread took 2 milliseconds to initialize
src/tier1/KeyValues.cpp (2967) : Assertion Failed: Error while parsing text KeyValues for resource InstallConfigStore
assert_20220128061834_11.dmp[2600]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220128061834_11.dmp
assert_20220128061834_11.dmp[2600]: Finished uploading minidump (out-of-process): success = no
assert_20220128061834_11.dmp[2600]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20220128061834_11.dmp[2600]: file ''/tmp/dumps/assert_20220128061834_11.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
src/tier1/KeyValues.cpp (2967) : Assertion Failed: Error while parsing text KeyValues for resource InstallConfigStore
src/tier1/KeyValues.cpp (2967) : Assertion Failed: Error while parsing text KeyValues for resource InstallConfigStore
```

**How to reproduce**

Unknown yet

-

**Expected behavior**

The steam deployment should run without errors after setting up per documentation

**Additional details**

Full Log
[logs_11.zip](https://github.com/game-ci/steam-deploy/files/7956275/logs_11.zip)
