### ISSUE TITLE
first line of 'run' command fails on Windows

### ISSUE THREAD

**Issue by samanpwbb** [game-ci/steam-deploy#34]
**Bug description**

When attempting to run steam-deploy on a window-latest machine via a GitHub workflow, I get the following error:

```
Run chmod +x D:\a\_actions\game-ci\steam-deploy\v1.1.0/steam_deploy.sh
chmod: cannot access 'D:a_actionsgame-cisteam-deployv1.1.0/steam_deploy.sh': No such file or directory
Error: Process completed with exit code 1.
```

**How to reproduce**

I have a step in my workflow that looks like this, and it triggers the failure:
```
      - name: Steam - Deploy Windows
        if: matrix.os == 'windows-latest'
        uses: game-ci/steam-deploy@v1.1.0
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
          ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
          appId: {{secrets.APP_ID}}
          buildDescription: ${{ github.ref }}
          rootPath: electron/out
          depot1Path: wilderplace-win32-x64
          releaseBranch: prerelease
```

**Expected behavior**

I expect the steam_deploy script to run on windows. 

**Additional details**

My game is built using Electron, and therefore I need to be running my build script on a Windows machine in order to build for Windows users. Ideally, I can use the same workflow to both build the Electron app, and upload it to Steam, all from a windows machine.
