### ISSUE TITLE
2FA auth fails on Mac only

### ISSUE THREAD

**Issue by samanpwbb** [game-ci/steam-deploy#35]
**Bug description**

Using 'macos-latest' and `game-ci/steam-deploy@v1.1.0`, I get a `Steam Guard code:FAILED (Account Logon Denied)` error when attempting to use this action in my workflow.

The action works as expected on `ubuntu-latest`.

**How to reproduce**

```
      - name: Steam - Deploy Mac
        if: matrix.os == 'macos-latest'
        uses: game-ci/steam-deploy@v1.1.0
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
          ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
          appId: {myappid}
          buildDescription: ${{ github.ref }}
          rootPath: electron/out
          depot1Path: wilderplace-darwin-x64
          releaseBranch: prerelease
```

**Expected behavior**

Upload succeeds.

I think the issue is caused by the fact that `STEAM_HOME` is not where macos expects to find the 2fa credentials: https://github.com/game-ci/steam-deploy/blob/main/action.yml#L79, which is used here: https://github.com/game-ci/steam-deploy/blob/main/steam_deploy.sh#L83-L100

`STEAM_HOME` comes from the directory where steamcmd is installed: https://github.com/CyberAndrii/setup-steamcmd/blob/master/src/index.js#L54

But on my mac, I think steamcmd expects credentials to be in `Library/Application Support/Steam/`.
