### ISSUE TITLE
Can we deploy to Steam without uploading and downloading the artifact to Github?

### ISSUE THREAD

**Issue by galfaroth** [game-ci/steam-deploy#59]
Basically I want to save money because each GB counts on Github. How to configure so that I don't upload and download the artifact?

**Comment by webbertakken** [comment]
Could you elaborate a bit more on what you're trying to do exactly?

**Comment by galfaroth** [comment]
Hey, im using self hosted Linux and I want not to upload and download artifact from GitHub to save money. Basically my builds are 10-15gb and I prefer to upload to Steam directly.

**Comment by webbertakken** [comment]
You have a few options here:

- Use a separate step in the same job, so that you can ensure the build and the upload are happening on the same runner. You can remove upload-artifact entirely.
- In case of a single self-hosted runner you could save the file on the runner itself (as it's effectively not ephemeral)
- In case of multiple runners I'd recommend using an answer from this discussion https://github.com/orgs/community/discussions/26165. At the time of writing, the answer involves hosting a file server locally. This is most likely your most flexible and scalable solution.

**Comment by galfaroth** [comment]
So here's set of actions that I created, what should I change to accomplish the first point? self-hosted, the same machine builds and deploys.

```
name: Actions 😎

on:
  push:
    branches:
      - build # Your branch goes here
jobs:
  buildForWindowsAndOSX:
    name: Build my project ✨
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - StandaloneOSX
    outputs:
      buildVersion: ${{ steps.build.outputs.buildVersion }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key:
            Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**',
            'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-
      - uses: game-ci/unity-builder@v2
        id: build
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  deployToSteam:
    needs: [buildForWindowsAndOSX]
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download StandaloneWindows64 Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64
      - name: Download StandaloneOSX Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneOSX
          path: build/StandaloneOSX
      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: v${{ needs.buildForWindowsAndOSX.outputs.buildVersion }}
          rootPath: build
          depot1Path: StandaloneWindows64
          depot2Path: StandaloneOSX
          releaseBranch: yyy
```

**Comment by davidmfinol** [comment]
Instead of splitting into 2 jobs, you could run everything on the same job?
IE: delete all the lines after `- uses: actions/upload-artifact@v3` and before `- uses: game-ci/steam-deploy@v3`
Does that work for you?

**Comment by trezy** [comment]
Just wanted to add my solution to this thread. I'm actually creating a Github Release before I build my app, and then uploading the build assets to the release. Then I download the assets to the new runner when it's time to publish to Steam. It turns out to be much faster than uploading/downloading artefacts, too.

Here's an example workflow (this is untested pseudocode - you'll need to update for your situation, e.g. some of these actions may not work on Windows runners):

```yml
name: Publish

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create a Release
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          body: BUILD_VERSION
          name: BUILD_VERSION
          tag: BUILD_VERSION
          token: ${{ secrets.GITHUB_TOKEN }}

  create-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Your Game Here
        run: echo 'Nothing to see here.'

      - name: Upload Assets to the Release
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          body: BUILD_VERSION
          files: |
            build/*.exe
          name: BUILD_VERSION
          tag: BUILD_VERSION
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-to-steam:
    runs-on: ubuntu-latest
    steps:
      - name: Download Assets from Release
        uses: robinraju/release-downloader@v1.8
        with:
          fileName: builds
          out-file-path: artifacts
          repository: ${{ github.repository }}
          tag: BUILD_VERSION
          token: ${{ github.token }}

      - name: Publish to Steam
        uses: game-ci/steam-deploy@v3
        with:
          username: ${{ env.STEAM_BUILD_USERNAME }}
          configVdf: ${{ env.STEAM_CONFIG_VDF }}
          appId: ${{ env.STEAM_APP_ID }}
          buildDescription: BUILD_VERSION
          rootPath: builds
          depot1Path: .
          releaseBranch: prerelease
```

**Comment by frostebite** [comment]
Yes, and you likely already don't need the GitHub-artifact round-trip: `actions/upload-artifact` + `download-artifact` is only necessary when the build and deploy steps run in **different jobs** (jobs don't share a filesystem). If you build and deploy in the **same job**, the build output is already on disk when the deploy step runs — no upload/download needed:

```yaml
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-builder@v4
        with: { targetPlatform: StandaloneWindows64 }
      - uses: game-ci/steam-deploy@v3
        with:
          rootPath: build
          depot1Path: StandaloneWindows64
          # ...
```

This is the standard pattern and avoids the GB-counted artifact transfer entirely. Splitting build and deploy into separate jobs is only worth it if you want to parallelize multiple platform builds before a single deploy job — in which case the artifact transfer is the cost of that parallelism, not something steam-deploy itself can avoid. Closing as answered — reopen if your setup specifically needs cross-job builds and still wants to avoid the artifact step, which would need a different mechanism (e.g. a self-hosted runner with a persistent shared volume).
