### ISSUE TITLE
Anytime it gets to steam-deploy step it fails with unable to find image

### ISSUE THREAD

**Issue by galfaroth** [game-ci/steam-deploy#60]
**Bug description**
It runs /usr/bin/docker run --name aaf5bf14427a5284475bf02669bf9afc85d_b0d92c --label 446aaf --workdir /github/workspace...

Then it errors with:

Unable to find image '446aaf:5bf14427a5284475bf02669bf9afc85d' locally
docker: Error response from daemon: pull access denied for 446aaf, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**How to reproduce**

Just run on latest build

-

**Expected behavior**

Deploy succeeds

**Additional details**

I tried standard script.

**Comment by webbertakken** [comment]
Are you running GitHub hosted runners or self-hosted?

Generally speaking this isn't a bug but a limitation by dockerhub. Basically they're requesting people to sign in to pull images over a certain rate.

Related question on StackOverflow: https://stackoverflow.com/questions/73297640/github-workflow-requested-access-to-the-resource-is-denied

**Comment by galfaroth** [comment]
Hey! Thank you for your fast reply. I'm using local runtime. I logged into docker but still see the same message. Can you give me the docker repo used for Steam deploy so that I first confirm that it downloads correctly onto my machine?

**Comment by webbertakken** [comment]
All you should have to do is sign in your docker CLI. After that your rate limit should be much higher.

**Comment by galfaroth** [comment]
Hey, I logged into docker using CLI, then I added this action: docker-login and it succeeded but still I get the same error. How can we debug it? Here's my action plan.


```
name: Actions 😎

# on: [push, pull_request]

on:
  push:
    branches:
      - build # Your branch goes here
  pull_request:
    branches:
      - build # Your branch goes here

jobs:
  buildForWindowsAndOSX:
    name: Build my project ✨
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - StandaloneOSX
    outputs:
      buildVersion: ${{ steps.build.outputs.buildVersion }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key:
            Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**',
            'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-
      - uses: game-ci/unity-builder@v2
        id: build
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  deployToSteam:
    needs: [buildForWindowsAndOSX]
    runs-on: self-hosted
    steps:
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download StandaloneWindows64 Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64
      - name: Download StandaloneOSX Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneOSX
          path: build/StandaloneOSX
      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: v${{ needs.buildForWindowsAndOSX.outputs.buildVersion }}
          rootPath: build
          depot1Path: StandaloneWindows64
          depot2Path: StandaloneOSX
          releaseBranch: yyy
```

**Comment by galfaroth** [comment]
I even tried adding Pull image command which successfully works but still get the same error on steam-deploy@v3
```
  deployToSteam:
    needs: [buildForWindowsAndOSX]
    runs-on: self-hosted
    steps:
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Image
        run: docker pull steamcmd/steamcmd:latest
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download StandaloneWindows64 Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64
      - name: Download StandaloneOSX Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneOSX
          path: build/StandaloneOSX
      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: v${{ needs.buildForWindowsAndOSX.outputs.buildVersion }}
          rootPath: build
          depot1Path: StandaloneWindows64
          depot2Path: StandaloneOSX
          releaseBranch: yyy
```

Here's full log:
```
Run game-ci/steam-deploy@v3
  with:
    username: ***
    configVdf: ***
  
    appId: ***
    buildDescription: v0.0.16
    rootPath: build
    depot1Path: StandaloneWindows64
    depot2Path: StandaloneOSX
    releaseBranch: yyy
/usr/bin/docker run --name aaf208158ce94a844759d991b5c0819ae20_b9e76b --label 446aaf --workdir /github/workspace --rm -e "INPUT_USERNAME" -e "INPUT_CONFIGVDF" -e "INPUT_APPID" -e "INPUT_BUILDDESCRIPTION" -e "INPUT_ROOTPATH" -e "INPUT_DEPOT1PATH" -e "INPUT_DEPOT2PATH" -e "INPUT_RELEASEBRANCH" -e "INPUT_TOTP" -e "INPUT_FIRSTDEPOTIDOVERRIDE" -e "INPUT_DEPOT3PATH" -e "INPUT_DEPOT4PATH" -e "INPUT_DEPOT5PATH" -e "INPUT_DEPOT6PATH" -e "INPUT_DEPOT7PATH" -e "INPUT_DEPOT8PATH" -e "INPUT_DEPOT9PATH" -e "steam_username" -e "steam_password" -e "steam_totp" -e "configVdf" -e "ssfnFileName" -e "ssfnFileContents" -e "appId" -e "firstDepotIdOverride" -e "buildDescription" -e "rootPath" -e "depot1Path" -e "depot2Path" -e "depot3Path" -e "depot4Path" -e "depot5Path" -e "depot6Path" -e "depot7Path" -e "depot8Path" -e "depot9Path" -e "releaseBranch" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/media/cvedia/STORAGE/scripts/actions-runner/_work/_temp/_github_home":"/github/home" -v "/media/cvedia/STORAGE/scripts/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/media/cvedia/STORAGE/scripts/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/media/cvedia/STORAGE/scripts/actions-runner/_work/xxx-xxx/xxx-xxx":"/github/workspace" 446aaf:208158ce94a844759d991b5c0819ae20
Unable to find image '446aaf:208158ce94a844759d991b5c0819ae20' locally
docker: Error response from daemon: pull access denied for 446aaf, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
