### ISSUE TITLE
Password: FAILED (Invalid Password)

### ISSUE THREAD

**Issue by timothymalcham** [game-ci/steam-deploy#62]
**Bug description**

I was having some issues authenticating with Steam Guard with v1 of this action, so I recently upgraded to v3 (I was told doing so might fix the issue). That issue is gone now, but now in the "Test login" step, I get this error: 

```
Run game-ci/steam-deploy@v3
/usr/bin/docker run --name c9a4a5b62624b2b5b644789d0f425748d4fd04_84366b --label c9a4a5 --workdir /github/workspace --rm -e "INPUT_USERNAME" -e "INPUT_CONFIGVDF" -e "INPUT_APPID" -e "INPUT_BUILDDESCRIPTION" -e "INPUT_ROOTPATH" -e "INPUT_DEPOT1PATH" -e "INPUT_DEPOT2PATH" -e "INPUT_RELEASEBRANCH" -e "INPUT_TOTP" -e "INPUT_FIRSTDEPOTIDOVERRIDE" -e "INPUT_DEPOT3PATH" -e "INPUT_DEPOT4PATH" -e "INPUT_DEPOT5PATH" -e "INPUT_DEPOT6PATH" -e "INPUT_DEPOT7PATH" -e "INPUT_DEPOT8PATH" -e "INPUT_DEPOT9PATH" -e "steam_username" -e "steam_password" -e "steam_totp" -e "configVdf" -e "ssfnFileName" -e "ssfnFileContents" -e "appId" -e "firstDepotIdOverride" -e "buildDescription" -e "rootPath" -e "depot1Path" -e "depot2Path" -e "depot3Path" -e "depot4Path" -e "depot5Path" -e "depot6Path" -e "depot7Path" -e "depot8Path" -e "depot9Path" -e "releaseBranch" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/DINO-MERCS-unity/DINO-MERCS-unity":"/github/workspace" c9a4a5:b62624b2b5b644789d0f425748d4fd04

#################################
#   Generating Depot Manifests  #
#################################


Adding depot1827641.vdf ...

"DepotBuildConfig"
{
  "DepotID" "1827641"
  "FileMapping"
  {
    "LocalPath" "./StandaloneWindows64/*"
    "DepotPath" "."
    "recursive" "1"
  }
  "FileExclusion" "*.pdb"
  "FileExclusion" "**/*_BurstDebugInformation_DoNotShip*"
  "FileExclusion" "**/*_BackUpThisFolder_ButDontShipItWithYourGame*"
}


Adding depot1827642.vdf ...

"DepotBuildConfig"
{
  "DepotID" "1827642"
  "FileMapping"
  {
    "LocalPath" "./StandaloneOSX/*"
    "DepotPath" "."
    "recursive" "1"
  }
  "FileExclusion" "*.pdb"
  "FileExclusion" "**/*_BurstDebugInformation_DoNotShip*"
  "FileExclusion" "**/*_BackUpThisFolder_ButDontShipItWithYourGame*"
}


#################################
#    Generating App Manifest    #
#################################

"appbuild"
{
  "appid" "***"
  "desc" "v2.0.11"
  "buildoutput" "BuildOutput"
  "contentroot" "/github/workspace/build"
  "setlive" "prerelease"

  "depots"
  {    "1827641" "depot1827641.vdf"    "1827642" "depot1827642.vdf"  }
}


#################################
#    Copying SteamGuard Files   #
#################################

Steam is installed in: /github/home/Steam
Copying /github/home/Steam/config/config.vdf...
Finished Copying SteamGuard Files!


#################################
#        Test login             #
#################################

ln: failed to create symbolic link '/github/home/.steam/root': No such file or directory
ln: failed to create symbolic link '/github/home/.steam/steam': No such file or directory
Redirecting stderr to '/github/home/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 59,540 KB)...
[  0%] Downloading update (0 of 59,540 KB)...
[  0%] Downloading update (0 of 59,540 KB)...
[  0%] Downloading update (3,304 of 59,540 KB)...
[  5%] Downloading update (7,013 of 59,540 KB)...
[ 11%] Downloading update (9,776 of 59,540 KB)...
[ 16%] Downloading update ([12](https://github.com/timothymalcham/DINO-MERCS-unity/actions/runs/5623993320/job/15260382456#step:6:13),284 of 59,540 KB)...
[ 20%] Downloading update (14,806 of 59,540 KB)...
[ 24%] Downloading update (17,3[13](https://github.com/timothymalcham/DINO-MERCS-unity/actions/runs/5623993320/job/15260382456#step:6:14) of 59,540 KB)...
[ 29%] Downloading update (20,067 of 59,540 KB)...
[ 33%] Downloading update (22,574 of 59,540 KB)...
[ 37%] Downloading update (25,094 of 59,540 KB)...
[ 42%] Downloading update (27,596 of 59,540 KB)...
[ 46%] Downloading update (30,350 of 59,540 KB)...
[ 50%] Downloading update (32,858 of 59,540 KB)...
[ 55%] Downloading update (35,369 of 59,540 KB)...
[ 59%] Downloading update (37,879 of 59,540 KB)...
[ 63%] Downloading update (40,509 of 59,540 KB)...
[ 68%] Downloading update (42,277 of 59,540 KB)...
[ 71%] Downloading update (43,537 of 59,540 KB)...
[ 73%] Downloading update (44,779 of 59,540 KB)...
[ 75%] Downloading update (46,034 of 59,540 KB)...
[ 77%] Downloading update (47,416 of 59,540 KB)...
[ 79%] Downloading update (48,669 of 59,540 KB)...
[ 81%] Downloading update (49,934 of 59,540 KB)...
[ 83%] Downloading update (51,320 of 59,540 KB)...
[ 86%] Downloading update (52,578 of 59,540 KB)...
[ 88%] Downloading update (53,831 of 59,540 KB)...
[ 90%] Downloading update (55,204 of 59,540 KB)...
[ 92%] Downloading update (56,456 of 59,540 KB)...
[ 94%] Downloading update (57,7[15](https://github.com/timothymalcham/DINO-MERCS-unity/actions/runs/5623993320/job/15260382456#step:6:16) of 59,540 KB)...
[ 96%] Downloading update (58,949 of 59,540 KB)...
[ 99%] Downloading update (59,540 of 59,540 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
Redirecting stderr to '/github/home/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/github/home/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version [16](https://github.com/timothymalcham/DINO-MERCS-unity/actions/runs/5623993320/job/15260382456#step:6:17)8964[25](https://github.com/timothymalcham/DINO-MERCS-unity/actions/runs/5623993320/job/15260382456#step:6:26)[31](https://github.com/timothymalcham/DINO-MERCS-unity/actions/runs/5623993320/job/15260382456#step:6:32)
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Logging in user '***' to Steam Public...
password: FAILED (Invalid Password)
```

From what I understand, we no longer have to pass the STEAM_PASSWORD secret, so what would cause this error? 

I've consistently gotten this error each time I run the workflow, resulting in the job failing and the build not making it to Steam. 

**Additional details**

```
name: 🚀 Build Game & Deploy to Steam 🚀

on:
    push:
        tags:
            - 'v*'

jobs:
  buildForWindowsMac:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneOSX # Build a OSX intel 64-bit standalone.
    outputs:
      buildVersion: ${{ steps.build.outputs.buildVersion }}
    steps:
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
         
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key:
            Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**',
            'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      - uses: game-ci/unity-builder@v2
        id: build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  deployToSteam:
    needs: [buildForWindowsMac]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download StandaloneWindows64 Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64

      - name: Download StandaloneOSX Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneOSX
          path: build/StandaloneOSX

      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: v${{ needs.buildForWindowsMac.outputs.buildVersion }}
          rootPath: build
          depot1Path: StandaloneWindows64
          depot2Path: StandaloneOSX
          releaseBranch: prerelease
```

**Comment by timothymalcham** [comment]
I tried recreating the `STEAM_CONFIG_VDF` secret once again, following the steps mentioned here: https://game.ci/docs/github/deployment/steam. But still get the invalid password error. 

Would this error be caused by a misconfigured secret?

**Comment by timothymalcham** [comment]
Okay I tried one more time to set the steam guard code and the vdf file, and it worked this time and the build succeeded. 

Not sure what was different this time. Feel free to close this issue out if it doesn't seem to affect anyone else.

**Comment by webbertakken** [comment]
Thanks for reporting in your solution as well!

I'll close this, but in case anyone is running into the same issue - or if the issue returns - by all means let's reopen it.

**Comment by mikeage** [comment]
FWIW, I've seen that I've needed to regenerate the config.vdf file several times in the past few weeks. Prior to this change (I use my own action, but the contents are the same), we had the same file from Oct 2021 until about 2 weeks ago. I have no idea why -- has anyone else seen this?

**Comment by bleakley** [comment]
I'm experiencing the same issue as well, calling v3 with the following args:

```
      - name: Steam - Deploy
        uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: ***
          buildDescription: ${{ github.ref_name }}
          rootPath: out
          depot1Path: warpvector-win32-x64
          depot2Path: warpvector-linux-x64
```

repeating many, many times as suggested. I'm getting

```
Logging in user '***' to Steam Public...
password: FAILED (Invalid Password)
```
but like the OP I am using v3 and not using the password. I was experiencing the identical issue on v2 as well when passing in the correct password.
