### ISSUE TITLE
Docker: Pull access denied, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by fajar-algorocks** [game-ci/steam-deploy#78]
**Bug description**

Unable to find image 'ec5079:5098b2a473f5478699c0bf0ea7fa5c49' locally
docker: Error response from daemon: pull access denied for ec5079, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**How to reproduce**

I'm not sure. I followed the instructions exactly.
The build action succeeds on its own, but when I add steam-deploy, it fails.

**Expected behavior**

The process should work as expected without errors.

**Additional details**

```
Run game-ci/steam-deploy@v3
  with:
    username: ***
    configVdf: ***
    appId: ***
    buildDescription: v
    rootPath: Builds/StandaloneWindows64
    depot1Path: StandaloneWindows64
    depot1InstallScriptPath: StandaloneWindows64/install_script.vdf
    releaseBranch: internal-dev
/usr/bin/docker run --name ec50795098b2a473f5478699c0bf0ea7fa5c49_b274db --label ec5079 --workdir /github/workspace --rm -e "INPUT_USERNAME" -e "INPUT_CONFIGVDF" -e "INPUT_APPID" -e "INPUT_BUILDDESCRIPTION" -e "INPUT_ROOTPATH" -e "INPUT_DEPOT1PATH" -e "INPUT_DEPOT1INSTALLSCRIPTPATH" -e "INPUT_RELEASEBRANCH" -e "INPUT_TOTP" -e "INPUT_FIRSTDEPOTIDOVERRIDE" -e "INPUT_DEPOT2PATH" -e "INPUT_DEPOT2INSTALLSCRIPTPATH" -e "INPUT_DEPOT3PATH" -e "INPUT_DEPOT3INSTALLSCRIPTPATH" -e "INPUT_DEPOT4PATH" -e "INPUT_DEPOT4INSTALLSCRIPTPATH" -e "INPUT_DEPOT5PATH" -e "INPUT_DEPOT5INSTALLSCRIPTPATH" -e "INPUT_DEPOT6PATH" -e "INPUT_DEPOT6INSTALLSCRIPTPATH" -e "INPUT_DEPOT7PATH" -e "INPUT_DEPOT7INSTALLSCRIPTPATH" -e "INPUT_DEPOT8PATH" -e "INPUT_DEPOT8INSTALLSCRIPTPATH" -e "INPUT_DEPOT9PATH" -e "INPUT_DEPOT9INSTALLSCRIPTPATH" -e "steam_username" -e "steam_totp" -e "configVdf" -e "appId" -e "firstDepotIdOverride" -e "buildDescription" -e "rootPath" -e "depot1Path" -e "depot1InstallScriptPath" -e "depot2Path" -e "depot2Insta
Unable to find image 'ec5079:5098b2a473f5478699c0bf0ea7fa5c49' locally
docker: Error response from daemon: pull access denied for ec5079, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

``` yml
name: Build Development

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildForSteam:
    name: Build [DEVELOPMENT]
    runs-on: ubuntu-latest
    outputs:
      buildVersion: ${{ steps.buildStep.outputs.buildVersion }}
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build StandaloneWindows64 Steam DEV
      - name: Build StandaloneWindows64 DEV
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: "AwesomeGame"
          buildsPath: 'Builds'
          customParameters: '-Development'

      # Direct Steam Deployment
      - name: Deploy to Steam
        uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: v${{ steps.buildStep.outputs.buildVersion }}
          rootPath: Builds/StandaloneWindows64
          depot1Path: StandaloneWindows64
          depot1InstallScriptPath: StandaloneWindows64/install_script.vdf
          releaseBranch: internal-dev
```
