### ISSUE TITLE
Cannot execute `steam-deploy` twice in the same CI job

### ISSUE THREAD

**Issue by soundasleep** [game-ci/steam-deploy#79]
**Bug description**

It seems that if you try to push to two branches in the same CI job, this action will fail in the second step with:

```
mkdir: cannot create directory ‘BuildOutput’: File exists
```

My guess is that at https://github.com/game-ci/steam-deploy/blob/main/steam_deploy.sh#L10 it's creating a new `BuildOutput` directory but it's never deleted.

**How to reproduce**

```yaml
    - name: Deploy to Steam (branch1)
      uses: game-ci/steam-deploy@v3
      with:
        username: ...
        configVdf: ...
        appId: ...
        buildDescription: todo
        rootPath: desktop/build
        depot2Path: package/
        releaseBranch: branch1
    - name: Deploy to Steam (branch2)
      uses: game-ci/steam-deploy@v3
      with:
        username: ...
        configVdf: ...
        appId: ...
        buildDescription: todo
        rootPath: desktop/build
        depot2Path: package/
        releaseBranch: branch2
```

**Expected behavior**

It should be possible to push the same build to two Steam branches within the same CI job.

**Additional details**

Potential workarounds:
- Maybe `steam-deploy` can `rm -rf BuildOutput` once the build has successfully uploaded
- Or the `BuildOutput` directory name is randomly generated per build
- Another workaround is probably running two CI jobs concurrently, one for each Steam branch, but https://github.com/game-ci/steam-deploy/issues/62#issuecomment-2409083082 reported that it may not be possible to upload two Steam branches at the same time

**Comment by webbertakken** [comment]
Did you try your suggestion of removing `BuildOutput` in between the steps?

If it resolves the issue we could maybe then add it to the start of the action.

**Comment by soundasleep** [comment]
Yes! I had to do a bit of `chown`ing first, otherwise the directory couldn't be deleted (it's created by `root:root`?) but this is my workaround:

```yaml
    - name: Deploy to Steam (branch1)
      uses: game-ci/steam-deploy@v3
      with:
        username: ...
        configVdf: ...
        appId: ...
        buildDescription: todo
        rootPath: desktop/build
        depot2Path: package/
        releaseBranch: branch1
    - name: Delete BuildOutput folder
      run: |
        whoami
        ls -la
        ls -la BuildOutput
        sudo chown -R $USER:$USER BuildOutput
        ls -la
        ls -la BuildOutput
        rm -rf BuildOutput
    - name: Deploy to Steam (branch2)
      uses: game-ci/steam-deploy@v3
      with:
        username: ...
        configVdf: ...
        appId: ...
        buildDescription: todo
        rootPath: desktop/build
        depot2Path: package/
        releaseBranch: branch2
```
