### ISSUE TITLE
ERROR! Content root folder does not exist even though the path files is alive . 

### ISSUE THREAD

**Issue by anothaiyoyo** [game-ci/steam-deploy#82]
When my job is already upload the build in Gitea it's seems to working great but when it's going to deploy to steam I think I already checked the path and the files is still existing , but I got the error  "root folder does not exist:" (I did the multiple build OSX , Window64 )

```
the YAML 
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LevelEditor-[${{ steps.get-version.outputs.version }} - ${{ matrix.targetPlatform }}]
          path: LevelEditor

      - name: Check if rootPath exists
        run: |
          echo "Checking root path for Steam Deploy: LevelEditor/${{ matrix.targetPlatform }}"
          ls -alh LevelEditor/${{ matrix.targetPlatform }}         
      
      - name: Check permissions and set them
        run: |
          chmod -R 755 LevelEditor

      - name: Deploy to Steam
        uses: game-ci/steam-deploy@v3.0.4
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          appId: ${{ matrix.targetPlatform == 'StandaloneWindows64' && '2576060' || '2576061' }}
          rootPath: LevelEditor
          buildDescription: "LevelEditor-[${{ steps.get-version.outputs.version }} - ${{ matrix.targetPlatform }}]"
          depot1Path: ${{ matrix.targetPlatform }} 
          firstDepotIdOverride: ${{ matrix.targetPlatform == 'StandaloneWindows64' && '2576060' || '2576061' }}
          depot1InstallScriptPath: ${{ matrix.targetPlatform }}/install_script.vdf

```

It should be found the LevelEditor path but when it's try to deploy I got 

#################################
#        Uploading build        #
#################################
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 17332695[77](http://192.168.32.146:3111/BitEgg/MYWORK/actions/runs/392#jobstep-11-77)
-- type 'quit' to exit --
Loading Steam API...OK
Logging in using cached credentials.
Logging in user '***' [U:1:1257754030] to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
[2024-12-11 04:50:16]: ERROR! Content root folder does not exist: /root/.cache/act/9666004f7167c1f5/hostexecutor/LevelEditor.

**Additional details**

I pretty sure that the path still existing when it's trying to deploy . 

any suggestion  about how can I re-config the .yaml files ?
