### ISSUE TITLE
Can we add more configVdf like configVdf1 & 2 ?

### ISSUE THREAD

**Issue by anothaiyoyo** [game-ci/steam-deploy#83]
Hi 
From  the example 

> jobs:
>   deployToSteam:
>     runs-on: ubuntu-latest
>     steps:
>       - uses: game-ci/steam-deploy@v3
>         with:
>           username: ${{ secrets.STEAM_USERNAME }}          
>           configVdf: ${{ secrets.STEAM_CONFIG_VDF}}          
>           appId: 1234560
>           buildDescription: v1.2.3
>           rootPath: build
>           depot1Path: StandaloneWindows64
>           depot1InstallScriptPath: StandaloneWindows64/install_script.vdf
>           depot2Path: StandaloneLinux64
>           releaseBranch: prerelease

the configVdf , can we add more dvf file ? since I have a multiple runner and I want it to run like 2-3  build at once  . 

Thank you .

**Comment by preeth1** [comment]
I had the same issue, I just forked the repo and added this functionality in myself:

https://github.com/game-ci/steam-deploy/compare/main...preeth1:steam-deploy:main


It does say in the readme to contribute if you have a more complex use case [here](https://github.com/game-ci/steam-deploy#firstdepotidoverride). FYI my branch is purely experimental and likely to change so I would not recommend referencing it directly in your github actions workflow file, rather you should probably make your own fork or your own PR to this repo!

**Comment by frostebite** [comment]
You don't need separate `configVdf1`/`configVdf2` inputs for this — the action (and the game-ci/cli `deploy steam` command it now wraps, see #92) is stateless per invocation, so multiple Steam accounts/apps just mean multiple steps in the same job, each with its own secrets:

```yaml
steps:
  - uses: game-ci/steam-deploy@v3
    with:
      username: ${{ secrets.STEAM_USERNAME_APP1 }}
      configVdf: ${{ secrets.STEAM_CONFIG_VDF_APP1 }}
      appId: 111111
      rootPath: build/app1

  - uses: game-ci/steam-deploy@v3
    with:
      username: ${{ secrets.STEAM_USERNAME_APP2 }}
      configVdf: ${{ secrets.STEAM_CONFIG_VDF_APP2 }}
      appId: 222222
      rootPath: build/app2
```

Each step gets its own GitHub secret pair (`STEAM_USERNAME_APP1`/`STEAM_CONFIG_VDF_APP1`, etc.) — no code change needed, and it already works today. Closing since this is achievable without new inputs, but let me know if you're hitting something this doesn't cover (e.g. wanting one `configVdf` shared across multiple app IDs on the *same* Steam account, which does already work as-is since `configVdf`/`username` are per-step and `appId` is independent).
