### ISSUE TITLE
Unable to deploy for problem with root path

### ISSUE THREAD

**Issue by PaoloAtRebelpug** [game-ci/steam-deploy#9]
Hello,

hope to find you well.

I am getting the following error when trying to use the full pipeline, is it possible that maybe the root path is relative and should be absolute?

> Loading Steam API...OK.
> Logging in user '***' to Steam Public ...
> Logged in OK
> Waiting for user info...OK
> [2021-04-22 14:57:49]: Starting AppID XXXXX build (flags 0x0).
> [2021-04-22 14:57:49]: Building depot XXXXX ...
> 
> Error! Invalid content root for depot XXXXX: /github/workspace/builds
> 
> [2021-04-22 14:57:49]: ERROR! Build for depot XXXXX failed : Failure

For the following pipeline:

```yaml

name: Test&Build

on: workflow_dispatch

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.4f1
        targetPlatform:
           - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - StandaloneWindows # Build a Windows 32-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: testRunner
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: builds
      - uses: game-ci/steam-deploy@v0.1
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          mfaCode:  ${{ secrets.STEAM_MFA_CODE }}
          appId: XXXXX
          buildDescription: v0.0.1
          rootPath: builds
          depot1Path: StandaloneWindows
          releaseBranch: test
          localContentServer: LocalContentServer
```

Thanks!
